package main

import (
	"archive/zip"
	"bytes"
	"embed"
	"fmt"
	"io/fs"
	"net/http"
)

// all: is required — plain embed skips files starting with _, and the plugin's
// _meta.lua is what makes KOReader load it at all.
//
//go:embed all:yata.koplugin
var pluginFS embed.FS

// pluginZipHandler serves the KOReader plugin already configured for this
// server: the user unzips it into koreader/plugins/ and never types a URL or a
// token on an e-ink keyboard, which is where self-hosted e-reader tooling
// usually gets abandoned.
func pluginZipHandler(cfg *config) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var buf bytes.Buffer
		zw := zip.NewWriter(&buf)

		err := fs.WalkDir(pluginFS, "yata.koplugin", func(p string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			b, err := pluginFS.ReadFile(p)
			if err != nil {
				return err
			}
			f, err := zw.Create(p)
			if err != nil {
				return err
			}
			_, err = f.Write(b)
			return err
		})
		if err == nil {
			var f interface{ Write([]byte) (int, error) }
			f, err = zw.Create("yata.koplugin/config.lua")
			if err == nil {
				_, err = fmt.Fprintf(f, "-- generated by yatagarasu, do not edit\nreturn { base_url = %q, api_key = %q }\n",
					publicURL(r, cfg), cfg.apiKey())
			}
		}
		if err == nil {
			err = zw.Close()
		}
		if err != nil {
			http.Error(w, "cannot build plugin zip", http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/zip")
		w.Header().Set("Content-Disposition", `attachment; filename="yata.koplugin.zip"`)
		w.Write(buf.Bytes())
	}
}

// publicURL prefers the configured one: behind a TLS-terminating reverse proxy
// r.Host and the scheme are both wrong, and a wrong base_url bakes a broken
// plugin that only fails on the device.
func publicURL(r *http.Request, cfg *config) string {
	if u := cfg.publicURL(); u != "" {
		return u
	}
	scheme := "http"
	if r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https" {
		scheme = "https"
	}
	return scheme + "://" + r.Host
}
