-- Yatagarasu — KOReader side of the Karasu shelf.
--
-- Downloads CBZ chapters from the shelf and reports finished ones back.
-- Two rules shape the whole plugin:
--   * sync is strictly additive; nothing here deletes a book because the shelf
--     stopped listing it (the shelf drops entries for reasons that have nothing
--     to do with the reader, e.g. Karasu's manga/chapter limits);
--   * "I finished this" is the only state that exists solely on the device, so
--     it is written to disk before it is sent, and cleared only on a 2xx.

local _ = require("gettext")
local DataStorage = require("datastorage")
local Device = require("device")
local DocSettings = require("docsettings")
local InfoMessage = require("ui/widget/infomessage")
local LuaSettings = require("luasettings")
local MultiInputDialog = require("ui/widget/multiinputdialog")
local NetworkMgr = require("ui/network/manager")
local Trapper = require("ui/trapper")
local UIManager = require("ui/uimanager")
local WidgetContainer = require("ui/widget/container/widgetcontainer")
local lfs = require("libs/libkoreader-lfs")
local logger = require("logger")
local util = require("util")
local Api = require("api")

-- Generated by the server into the ZIP it serves at /plugin.zip. Absent when
-- the plugin is copied by hand, which is fine: the menu can set both fields.
local ok_config, config = pcall(require, "config")
if not ok_config then
  config = {}
end

local Yata = WidgetContainer:extend({
  name = "yata",
  is_doc_only = false,
})

function Yata:init()
  self.settings = LuaSettings:open(DataStorage:getSettingsDir() .. "/yata.lua")
  self.manifest = self.settings:readSetting("manifest", {}) -- [path] = chapterId
  self.pending = self.settings:readSetting("pending", {}) -- [chapterId] = true, not yet reported
  self.acked = self.settings:readSetting("acked", {}) -- [chapterId] = true, shelf has it
  self.api = Api:new({
    base_url = self.settings:readSetting("base_url") or config.base_url or "",
    api_key = self.settings:readSetting("api_key") or config.api_key or "",
  })
  self.auto_task = function()
    self:autoSync()
  end
  self:scheduleAuto()
  self.ui.menu:registerToMainMenu(self)
end

function Yata:autoHours()
  return self.settings:readSetting("auto_hours") or 0
end

function Yata:setAutoHours(hours)
  self.settings:saveSetting("auto_hours", hours)
  self.settings:flush()
  self:scheduleAuto()
end

-- The clock runs from the last sync, not from startup: an e-reader is rebooted
-- often enough that a fresh interval on every boot means never syncing at all.
function Yata:scheduleAuto()
  UIManager:unschedule(self.auto_task)
  local hours = self:autoHours()
  if hours <= 0 then
    return
  end
  local delay = (self.settings:readSetting("last_auto") or 0) + hours * 3600 - os.time()
  if delay < 60 then
    delay = 60 -- overdue, but not while the reader is still opening
  end
  UIManager:scheduleIn(delay, self.auto_task)
end

function Yata:autoDue()
  local hours = self:autoHours()
  return hours > 0 and os.time() - (self.settings:readSetting("last_auto") or 0) >= hours * 3600
end

-- Runs with no UI at all: the transfers happen in a subprocess (see fetch()),
-- so the reader keeps painting and turning pages while it works, and a tap
-- cancels the chapter in flight without the user ever knowing there was one.
--
-- Only when the Wi-Fi is already up: a background timer that switches the
-- radio on drains a battery that was meant to last weeks. The due check is
-- here rather than at each caller, so the timer and the network event cannot
-- both fire a sync in the same minute.
function Yata:autoSync()
  if not (self:autoDue() and self.api.base_url ~= "" and NetworkMgr:isOnline() and not self.syncing) then
    self:scheduleAuto()
    return
  end
  self.syncing = true
  Trapper:wrap(function()
    local ok, result, err = pcall(function()
      return self:sync()
    end)
    self.syncing = false
    if ok and result then
      self.settings:saveSetting("last_auto", os.time())
      self.settings:flush()
    else
      logger.warn("yata: automatic sync did not run:", result or err)
    end
    self:scheduleAuto()
  end)
end

function Yata:onCloseWidget()
  UIManager:unschedule(self.auto_task)
end

function Yata:addToMainMenu(menu_items)
  menu_items.yata = {
    text = _("Yatagarasu"),
    sorting_hint = "tools",
    sub_item_table = {
      {
        text = _("Sync now"),
        callback = function()
          self:syncWithUI()
        end,
      },
      {
        text = _("Sync automatically"),
        sub_item_table = self:autoMenu(),
        separator = true,
      },
      {
        text = _("Shelf address and API key"),
        keep_menu_open = true,
        callback = function()
          self:editServer()
        end,
      },
      {
        text = _("Download folder"),
        keep_menu_open = true,
        callback = function()
          require("ui/downloadmgr")
            :new({
              title = _("Choose download folder"),
              onConfirm = function(path)
                self.settings:saveSetting("folder", path)
                self.settings:flush()
              end,
            })
            :chooseDir(self:folder())
        end,
      },
      {
        text = _("Remove finished downloads"),
        keep_menu_open = true,
        callback = function()
          self:removeFinishedDownloads()
        end,
        separator = true,
      },
      -- Karasu reshapes pages before uploading, but it cannot know how wide
      -- this screen is: the number has to be typed in over there. Showing it
      -- here is the whole reason that setting is usable.
      {
        text = string.format(_("Screen width: %d px"), Device.screen:getWidth()),
        keep_menu_open = true,
        callback = function()
          UIManager:show(InfoMessage:new({
            text = string.format(
              _(
                "This screen is %d × %d px.\n\nIn Karasu, under Settings → Yatagarasu, set Screen width to %d. Pages are then scaled and split for this device before they are uploaded, instead of arriving as one unreadable strip.\n\nChapters already on the shelf keep the shape they were uploaded with."
              ),
              Device.screen:getWidth(),
              Device.screen:getHeight(),
              Device.screen:getWidth()
            ),
          }))
        end,
      },
    },
  }
end

-- Only runs when the device is already online, so "every 6 hours" means "at
-- the first of those moments the Wi-Fi happens to be up".
function Yata:autoMenu()
  local choices = {
    { 0, _("Off") },
    { 6, _("Every 6 hours") },
    { 12, _("Every 12 hours") },
    { 24, _("Once a day") },
  }
  local items = {}
  for _idx, choice in ipairs(choices) do
    local hours = choice[1]
    table.insert(items, {
      text = choice[2],
      keep_menu_open = true,
      checked_func = function()
        return self:autoHours() == hours
      end,
      callback = function()
        self:setAutoHours(hours)
      end,
    })
  end
  return items
end

function Yata:folder()
  return self.settings:readSetting("folder")
    or G_reader_settings:readSetting("download_dir")
    or G_reader_settings:readSetting("lastdir")
    or DataStorage:getDataDir()
end

function Yata:editServer()
  local dialog
  dialog = MultiInputDialog:new({
    title = _("Yatagarasu shelf"),
    fields = {
      { description = _("Shelf address"), text = self.api.base_url, hint = "http://192.168.1.10:3080" },
      { description = _("API key (blank if none)"), text = self.api.api_key },
    },
    buttons = {
      {
        {
          text = _("Cancel"),
          id = "close",
          callback = function()
            UIManager:close(dialog)
          end,
        },
        {
          text = _("Save"),
          callback = function()
            local fields = dialog:getFields()
            self.api.base_url = (fields[1] or ""):gsub("%s+$", "")
            self.api.api_key = fields[2] or ""
            self.settings:saveSetting("base_url", self.api.base_url)
            self.settings:saveSetting("api_key", self.api.api_key)
            self.settings:flush()
            UIManager:close(dialog)
          end,
        },
      },
    },
  })
  UIManager:show(dialog)
  dialog:onShowKeyboard()
end

function Yata:root()
  return self:folder() .. "/Karasu"
end

-- <download folder>/Karasu/<manga>/<chapter>.cbz — one folder per manga,
-- because a flat folder with three dozen chapters is unusable in the file
-- browser. Returns the directory too, since the caller has to create it.
--
-- Human-readable names; the chapter id lives in the manifest and never in a
-- path. A user renaming a file must not be able to report the wrong chapter.
function Yata:pathFor(entry)
  local root = self:root()
  local dir = root .. "/" .. util.getSafeFilename(entry.mangaTitle or "manga", root)
  local name = string.format("%s.cbz", entry.chapterName or entry.chapterId)
  return dir .. "/" .. util.getSafeFilename(name, dir), dir
end

-- Where this chapter already is, wherever that is. The manifest is the answer
-- and not pathFor(), so chapters downloaded under an older naming scheme are
-- recognised instead of downloaded a second time.
function Yata:localPathFor(chapter_id)
  for path, id in pairs(self.manifest) do
    if id == chapter_id and lfs.attributes(path, "mode") then
      return path
    end
  end
end

function Yata:save()
  self.settings:saveSetting("manifest", self.manifest)
  self.settings:saveSetting("pending", self.pending)
  self.settings:saveSetting("acked", self.acked)
  self.settings:flush()
end

-- Sync is strictly additive: nothing in here removes a local file.
--
-- progress(i, total, title) is optional; returning false from it stops the run
-- where it stands, which is how a dismissed message aborts the rest. The
-- background sync passes nothing and is silent.
function Yata:sync(progress)
  if self.api.base_url == "" then
    return nil, _("Shelf address is not set.")
  end

  self:flushPending() -- read state reaches the shelf before Karasu's next pull

  local entries, err = self.api:shelf()
  if not entries then
    return nil, err
  end

  local downloaded, failed, no_space, cancelled = 0, 0, 0, false
  for i, entry in ipairs(entries) do
    local have = self:localPathFor(entry.chapterId)
    if have then
      self.manifest[have] = entry.chapterId
    else
      local path, dir = self:pathFor(entry)
      if lfs.attributes(path, "mode") then
        self.manifest[path] = entry.chapterId -- on disk, but not in the manifest
      elseif not self:hasRoomFor(entry.size) then
        no_space = no_space + 1
      elseif progress and progress(i, #entries, entry.mangaTitle) == false then
        cancelled = true -- the message was dismissed
        break
      else
        util.makePath(dir)
        local ok, dismissed = self:fetch(entry, path)
        if dismissed then
          cancelled = true
          break
        elseif ok then
          self.manifest[path] = entry.chapterId
          downloaded = downloaded + 1
        else
          failed = failed + 1
        end
      end
    end
  end
  self:save()

  self:sweepFinished()
  return {
    downloaded = downloaded,
    failed = failed,
    no_space = no_space,
    cancelled = cancelled,
    total = #entries,
  }
end

-- The transfer is the only part of a sync that takes real time, so it runs in
-- a forked subprocess while Trapper polls it from the UI loop: the screen keeps
-- painting and pages keep turning through a 60 MB download.
--
-- The child cannot change anything in this process, so it does the one thing
-- that lives on disk — writing the file — and the manifest is updated back here
-- from its answer. Being killed mid-transfer is safe by construction: the .part
-- file stays and the next sync resumes from it.
--
-- An invisible trap widget with no text means a tap cancels the chapter in
-- flight *and* is resent, so a background sync cannot swallow a page turn.
function Yata:fetch(entry, path)
  if not Trapper:isWrapped() then
    return self.api:download(entry.chapterId, path, entry.size), false
  end
  local api, id, size = self.api, entry.chapterId, entry.size
  local completed, answer = Trapper:dismissableRunInSubprocess(function()
    return api:download(id, path, size) and "ok" or "failed"
  end, nil, true)
  if not completed then
    return false, true
  end
  return answer == "ok", false
end

-- Chapters are tens of megabytes and e-readers are not generous with storage.
-- A download that fills the last of it takes the reader down with it, so a
-- chapter that does not fit is skipped and reported rather than attempted.
-- The margin is there because the filesystem needs room to breathe too.
function Yata:hasRoomFor(size)
  if not size or size <= 0 then
    return true
  end
  util.makePath(self:root()) -- diskUsage needs a directory that exists
  local usage = util.diskUsage(self:root())
  if not usage or not usage.available then
    return true -- unknown on this platform: not a reason to refuse
  end
  return usage.available > size + 10 * 1024 * 1024
end

function Yata:syncWithUI()
  if self.syncing then
    UIManager:show(InfoMessage:new({ text = _("A sync is already running."), timeout = 3 }))
    return
  end
  NetworkMgr:runWhenOnline(function()
    -- Trapper runs this as a coroutine: the progress message can be dismissed,
    -- and the downloads it drives do not block the reader.
    Trapper:wrap(function()
      self.syncing = true
      -- Reporting read chapters and fetching the listing come first and take a
      -- moment: without this the screen sits blank until a download starts.
      Trapper:info(_("Syncing with the shelf…"))
      local ok, result, err = pcall(function()
        return self:sync(function(i, total, title)
          -- false once the user dismisses and confirms: stop where we are.
          return Trapper:info(string.format(_("Downloading %d of %d…\n%s"), i, total, title or ""))
        end)
      end)
      self.syncing = false
      Trapper:clear()
      self:reportSync(ok, result, err)
    end)
  end)
end

function Yata:reportSync(ok, result, err)
  if not ok then
    logger.err("yata: sync crashed:", result)
    UIManager:show(InfoMessage:new({ text = _("Sync failed: ") .. tostring(result), timeout = 5 }))
    return
  end
  if not result then
    UIManager:show(InfoMessage:new({ text = _("Sync failed: ") .. tostring(err), timeout = 5 }))
    return
  end
  UIManager:show(InfoMessage:new({
    text = string.format(
      _("%s\n%d downloaded, %d on the shelf%s%s"),
      result.cancelled and _("Sync stopped.") or _("Sync done."),
      result.downloaded,
      result.total,
      result.failed > 0 and string.format(_(", %d failed"), result.failed) or "",
      result.no_space > 0 and string.format(_(", %d skipped for lack of space"), result.no_space) or ""
    ),
    timeout = 5,
  }))
end

-- Live path: KOReader fires this when the last page is turned.
function Yata:onEndOfBook()
  local file = self.ui and self.ui.document and self.ui.document.file
  local id = file and self.manifest[file]
  if id then
    self:reportFinished(id)
  end
end

-- Wi-Fi coming back is the first chance to deliver what was finished offline,
-- and it costs nothing on the usual path where there is nothing queued.
function Yata:onNetworkConnected()
  if self.api.base_url == "" then
    return
  end
  if next(self.pending) then
    self:flushPending()
  end
  -- A device that was offline when the timer fired would otherwise wait a whole
  -- interval more, which on a reader that only sees Wi-Fi at home means never.
  self:autoSync()
end

-- Offline path: books get finished with Wi-Fi off, so re-check everything we
-- know about on every sync. Re-reporting is free because the shelf is idempotent.
function Yata:sweepFinished()
  for path, id in pairs(self.manifest) do
    if not lfs.attributes(path, "mode") then
      self.manifest[path] = nil -- deleted or renamed: stop tracking it
    elseif self:isComplete(path) then
      self:reportFinished(id)
    end
  end
  self:save()
end

-- The reader writes its own "complete" status into the document's sidecar.
-- hasSidecarFile first: a book that was never opened has no sidecar, and
-- opening one would create it.
function Yata:isComplete(path)
  if not DocSettings:hasSidecarFile(path) then
    return false
  end
  local ok, summary = pcall(function()
    return DocSettings:open(path):readSetting("summary")
  end)
  return ok and type(summary) == "table" and summary.status == "complete"
end

-- On disk BEFORE the network: a crash or a dropped connection must not lose
-- the one piece of state that exists only here.
function Yata:reportFinished(id)
  local key = tostring(id)
  if self.acked[key] then
    return
  end
  self.pending[key] = true
  self:save()
  self:flushPending() -- best effort; failing is normal and harmless
end

function Yata:flushPending()
  local changed = false
  for key in pairs(self.pending) do
    if self.api:markRead(key) then
      self.pending[key] = nil
      self.acked[key] = true
      changed = true
    end
  end
  if changed then
    self:save()
  end
end

-- Deletion is explicit and has a rule the user can predict: only files whose
-- read report the shelf already acknowledged. That is strictly safer than
-- "gone from the shelf", which also happens to books still being read.
function Yata:removeFinishedDownloads()
  local removed = 0
  for path, id in pairs(self.manifest) do
    if self.acked[tostring(id)] then
      os.remove(path)
      if DocSettings:hasSidecarFile(path) then
        DocSettings:open(path):purge() -- drop the sidecar too
      end
      self.manifest[path] = nil
      self.acked[tostring(id)] = nil
      removed = removed + 1
      -- rmdir only succeeds on an empty folder, which is exactly the condition
      -- for wanting the manga gone from the browser.
      local dir = path:match("^(.*)/[^/]*$")
      if dir then
        lfs.rmdir(dir)
      end
    end
  end
  self:save()
  UIManager:show(InfoMessage:new({
    text = string.format(_("Removed %d finished chapter(s)."), removed),
    timeout = 3,
  }))
end

return Yata
